version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: education-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./server
    container_name: education-api
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://db:27017/education
      - CLOUDINARY_CLOUD_NAME=dxputzbkv
      - CLOUDINARY_API_KEY=214482875827562
      - CLOUDINARY_API_SECRET=KTQXxtap8QLTzIqJ6aL4K6xgL58

volumes:
  mongo-data: